#!/bin/bash

# `install-emacs'
# --------------------------------------------------------------------
# This script install Emacs 25+ on CI systems from official sources.
# See README.org in this directory.

if [ -z "${CI}" ]; then
    printf "This script should not be used locally\n"
    exit 1
fi

if [ -z "${EMACS_VERSION}" ]; then
    printf "EMACS_VERSION not set\n"
    exit 1
fi

if [ -z "${EMACS_DIR}" ]; then
    printf "EMACS_DIR not set\n"
    exit 1
fi

pushd . >/dev/null

if [ "${EMACS_VERSION}" == "snapshot" ]; then
    # https://git.savannah.gnu.org/git/emacs.git
    # https://github.com/emacs-mirror/emacs.git
    rm -rf "{$EMACS_DIR}"
    git clone --depth=1 "${EMACS_GIT_URL:-https://git.savannah.gnu.org/git/emacs.git}" "${EMACS_DIR}"
    cd "${EMACS_DIR}"
    ./autogen.sh
else
    # but make sure to abort if Emacs has already been created
    if [ -e "${EMACS_DIR}/src/emacs" ]; then
        printf "Emacs found at ${EMACS_DIR}/src/emacs; abort\n"
        exit 0
    fi
    TAR_NAME="emacs-${EMACS_VERSION}.tar.xz"
    REMOTE="https://ftp.gnu.org/gnu/emacs/${TAR_NAME}"
    PARENT="${EMACS_DIR%/*}"
    printf "Pulling Emacs from \"${REMOTE}\"\n"
    curl -o "${HOME}/${TAR_NAME}" "${REMOTE}"
    mkdir -p "${PARENT}"
    cd "${PARENT}"
    tar xf "${HOME}/${TAR_NAME}"
    mv "emacs-${EMACS_VERSION}" "${EMACS_DIR##*/}"
    cd "${EMACS_DIR##*/}"
fi

# provide default configuration flags
if [ -z "${EMACS_CONFIGURE_ARGS}" ]; then
    EMACS_CONFIGURE_ARGS="--with-x-toolkit=no --without-x --without-all --with-xml2 --with-modules"
fi

printf "Building Emacs with configuration: ${EMACS_CONFIGURE_ARGS}\n"
./configure ${EMACS_CONFIGURE_ARGS}
${MAKE:-make} -j4

popd >/dev/null

exit 0
